services:
  restaurantsdb:
    container_name: restaurantsdb
    environment:
      - ACCEPT_EULA=1
      - MSSQL_SA_PASSWORD=SwN@12345678
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sql-data:/var/opt/mssql

  redis:
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  seq:
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
      - $HOST_PATH_TO_SEQ:/data
    restart: always
    ports:
      - "5341:5341"
      - "81:80"
    volumes:
      - seq-data:/data
