@host = http://localhost
@port = 5146
@Restaurants.API_HostAddress = https://localhost:7264

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Accept: application/json

###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Content-Type: application/json

{
  "name": "McDonalds",
  "description": "McDonalds Corporation",
  "category": "Fast Food",
  "hasDelivery": true,
  "contactEmail": "admin@mcdonalds.com",
  "contactNumber": "1-200-376-9085",
  "city": "California",
  "street": "1178 Prospect Valley Road",
  "postalCode": "90220"
}

###
