@host = http://localhost
@port = 5146
@Restaurants.API_HostAddress = https://localhost:7264

GET {{Restaurants.API_HostAddress}}/api/restaurants
Accept: application/json

###

@id=1
GET {{Restaurants.API_HostAddress}}/api/restaurants/{{id}}
Accept: application/json

###
