@host = http://localhost
@port = 5146
@Restaurants.API_HostAddress = {{host}}:{{port}}
@weatherforecastEndPoint ={{Restaurants.API_HostAddress}}/api/weatherforecast/

GET {{weatherforecastEndPoint}}
Accept: application/json

###
