name: restaurats-api-ci

on:
  push:
    branches:
    - main
  pull_request:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_PATH: .\src\Restaurants.API
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore ${{env.PROJECT_PATH}}
      - name:  Build
        run: dotnet build --no-restore ${{env.PROJECT_PATH}}
      - name: Test
        run: dotnet test Restaurants.sln
