name: restaurants-api-pipeline

on:
  push:
    branches: 
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      PROJECT_PATH: ./src/Restaurants.API
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.3.0
        with:
          dotnet-version: '8.x'
      - name: Restore dependencies
        run: dotnet restore ${{env.PROJECT_PATH}}
      - name:  Build
        run: dotnet build --no-restore ${{env.PROJECT_PATH}} -c Release
      - name: Publish
        run: dotnet publish ${{env.PROJECT_PATH}} -c Release -o "${{env.DOTNET_ROOT}}/api" --no-build
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4.6.0
        with:
          name: api-artifact
          path: ${{env.DOTNET_ROOT}}/api

  deploy-dev:
    environment: 
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: api-artifact
      - name : Deploy to Azure Web App
        uses: Azure/webapps-deploy@v3.0.1
        id: deploy-to-webapp
        with:
          app-name: 'restaurants-api-dev-awatts'
          publish-profile:  ${{ secrets.PUBLISH_PROFILE_DEV }}

  deploy-prod:
    environment: 
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: api-artifact
      - name : Deploy to Azure Web App
        uses: Azure/webapps-deploy@v3.0.1
        id: deploy-to-webapp
        with:
          app-name: 'restaurants-api-prod-awatts'
          publish-profile:  ${{ secrets.PUBLISH_PROFILE_PROD  }}
